version: "2"

services: 
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/certs:/etc/nginx/certs
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: always

  redis:
    image: redis:2.8

  db-s1:
    image: mariadb
    container_name: aib-db-s1
    restart: always
    volumes: 
      - ./db/mysql1:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL-PWD
      MYSQL_DATABASE: aib_db

  db-s2:
    image: mariadb
    container_name: aib-db-s2
    restart: always
    volumes: 
      - ./db/mysql2:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL-PWD
      MYSQL_DATABASE: aib_db

  db-s3:
    image: mariadb
    container_name: aib-db-s3
    restart: always
    volumes: 
      - ./db/mysql3:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL-PWD
      MYSQL_DATABASE: aib_db

  db-dev:
    image: mariadb
    container_name: aib-db-dev
    restart: always
    volumes: 
      - ./db/mysql4:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL-PWD
      MYSQL_DATABASE: aib_db

  django-aib-s1:
    build: ./s1
    links:
      - "db-s1"
    restart: always
    container_name: django-aib-s1
    environment:
      DJANGO_SECRET_KEY: DJANGO-SECRET-KEY
      DJANGO_HOST_NAME: s1.artinbar.es
      MYSQL_DB: aib_db
      MYSQL_HOST: db-s1
      DEBUG: 'True'
      REDIS_HOST: redis
      VIRTUAL_HOST: s1.artinbar.es

  django-aib-s2:
    build: ./s2
    links:
      - "db-s2"
    restart: always
    container_name: django-aib-s2
    environment:
      DJANGO_SECRET_KEY: DJANGO-SECRET-KEY
      DJANGO_HOST_NAME: s2.artinbar.es
      MYSQL_DB: aib_db
      MYSQL_HOST: db-s2
      DEBUG: 'True'
      VIRTUAL_HOST: s2.artinbar.es
  
  django-aib-s3:
    build: ./s3
    links:
      - "db-s3"
    restart: always
    container_name: django-aib-s3
    environment:
      DJANGO_SECRET_KEY: DJANGO-SECRET-KEY
      DJANGO_HOST_NAME: artinbar.es, s3.artinbar.es
      LETSENCRYPT_HOST: artinbar.es, s3.artinbar.es
      LETSENCRYPT_EMAIL: trarsheise@gmail.com
      MYSQL_DB: aib_db
      MYSQL_HOST: db-dev
      DEBUG: 'False'
      HTTPS: 'True'
      REDIS_HOST: redis
      VIRTUAL_HOST: artinbar.es, s3.artinbar.es

  django-aib-dev:
    build: ./dev
    links:
      - "db-dev"
      - "redis"
    restart: always
    container_name: django-aib-dev
    environment:
      DJANGO_SECRET_KEY: DJANGO-SECRET-KEY
      DJANGO_HOST_NAME: dev.artinbar.es
      LETSENCRYPT_HOST: dev.artinbar.es
      LETSENCRYPT_EMAIL: trarsheise@gmail.com
      MYSQL_DB: aib_db
      MYSQL_HOST: db-dev
      DEBUG: 'True'
      HTTPS: 'True'
      REDIS_HOST: redis
      VIRTUAL_HOST: dev.artinbar.es