version: "2"

services: 
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=localhost
      - HTTPS_METHOD=noredirect
    restart: always

  db:
    image: mariadb
    container_name: aib-db
    restart: always
    volumes: 
      - ./db/mysql:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL-PWD
      MYSQL_DATABASE: aib_db

  django-aib:
    build: .
    links:
      - "db"
      - "redis"
    restart: always
    container_name: django-aib
    environment:
      DJANGO_SECRET_KEY: DJANGO-SECRET-KEY
      DJANGO_HOST_NAME: localhost
      MYSQL_DB: aib_db
      # MYSQL_USER:
      # MYSQL_PWD:
      MYSQL_HOST: db
      # MYSQL_PORT:
      DEBUG: 'True'
      REDIS_HOST: redis
      VIRTUAL_HOST: localhost