version: "2"

services: 
  db:
    image: mariadb
    container_name: aib-db
    restart: always
    volumes: 
      - ./db/mysql:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL-PWD
      MYSQL_DATABASE: aib_db

  django-aib:
    build: .
    links:
      - "db"
    restart: always
    container_name: django-aib
    ports:
      - '80:80'
    environment:
      DJANGO_SECRET_KEY: DJANGO-SECRET-KEY
      DJANGO_HOST_NAME: localhost
      MYSQL_DB: aib_db
      # MYSQL_USER:
      # MYSQL_PWD:
      MYSQL_HOST: db
      # MYSQL_PORT:
      DEBUG: 'True'