# Generated by Django 2.0.3 on 2018-03-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sentMessages',
        ),
        migrations.AddField(
            model_name='user',
            name='receivers',
            field=models.ManyToManyField(related_name='senders', through='mvp.Message', to='mvp.User'),
        ),
    ]
