# Generated by Django 2.0.4 on 2018-04-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_payment_paypalid'),
        ('mvp', '0002_feedback'),
    ]

    operations = [
    ]
