# Generated by Django 2.0.4 on 2018-06-07 02:06

import django.core.validators
from django.db import migrations, models
import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_merge_20180428_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistNumber',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offeredAmount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.FileField(null=True, upload_to=mvp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
