# Generated by Django 2.0.4 on 2018-06-07 16:18

from django.db import migrations, models
import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_auto_20180607_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.FileField(upload_to=mvp.models.photos_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.FileField(null=True, upload_to=mvp.models.logos_directory_path),
        ),
    ]
