# Generated by Django 2.0.5 on 2018-06-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0005_auto_20180606_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logo',
            new_name='Image',
        ),
    ]
